spring:
  security:
    user:
      name: user
      password: pwd

  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: org.h2.Driver

hello:
  string: "Hello, default profile"
---

spring:
  profiles: dev

  datasource:
    url: #{JDBC_DATABASE_URL}
    #driver-class-name: org.postgresql.Driver

hello:
  string: "Hello, dev profile"

---

spring:
  profiles: production

  datasource:
    url: #{JDBC_DATABASE_URL}
#    driver-class-name: org.postgresql.Driver
    driver-class-name: org.h2.Driver

hello:
  string: "Hello, production profile"
