spring:
  security:
    user:
      name: user
      password: pwd

  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: org.h2.Driver

---

spring:
  profiles: dev

  datasource:
    url: #{JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver